spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/risk_management
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

logging:
  level:
    com.assessment.riskmanagement: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
